#include <stdbool.h>

/*
 * Initiates pseudo random transmition 2FSK mode. 
 * In this mode a random data are generated by the internal pseudo-random generator.
 * Modulation type is 2FSK, where two different frequencies are used so the generated stream will be hearable
 * on FM receiver.
 */
bool fsk_init_tx_pseudo_sync_2fsk();

/*
 * Initiates direct synchronised transmition 2FSK mode. 
 * In this mode the bits must be fed to the transceiver by driving its GPIO0 pin.
 * Modulation type is 2FSK, where two different frequencies are used so the generated stream will be hearable
 * on FM receiver.
 */
bool fsk_init_tx_direct_sync_2fsk();

/*
 * Initiates direct synchronised transmition 2GFSK mode. 
 * In this mode the bits must be fed to the transceiver by driving its GPIO0 pin.
 * Modulation type is 2GFSK, where two different frequencies are used so the generated stream will be hearable
 * on FM receiver.
 */
bool fsk_init_tx_direct_sync_2gfsk();

/*
 * Starts the FSK transmition on specific channel.
 */
bool fsk_start_tx(uint8_t channel);

/*
 * Stops the FSK transmition.
 */
bool fsk_stop_tx();

bool afsk_tone(uint16_t freqHz, unsigned long durationUs);

bool afsk_send_aprs_byte(char byte);
