#include <stdbool.h>

/*
 * Initiates the fake F3E mode. In this mode a random data are generated by the internal pseudo-random generator.
 * Modulation type is 2FSK, where two different frequencies are used so the generated stream will be hearable
 * on PMR 446 FM receiver.
 */
bool fake_f3e_init_tx();

/*
 * Starts the fake F3E pseudo-random transmition.
 */
bool fake_f3e_start_tx();

/*
 * Stops the fake F3E pseudo-random transmition.
 */
bool fake_f3e_stop_tx();

bool fake_f3e_tone(uint16_t freqHz, unsigned long durationUs);

bool fake_f3e_send_aprs_byte(char byte);
