//#include "../examples/CWTransmitter/CWTransmitter.c"
//#include "../examples/OOKTransmitter/OOKTransmitter.c"
//#include "../examples/AFSKTransmitter/AFSKTransmitter.c"
//#include "../examples/AFSKAprsTransmitter/AFSKAprsTransmitter.c"
//#include "../examples/MelodyPlayer/MelodyPlayer.c"
#include "../examples/FoxTransmitter/FoxTransmitter.c"